name: dev

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16      

    - name: Build App
      run: |
          yarn --frozen-lockfile
          yarn build:win64
          yarn build-update


    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: v2rayN
        path: 
          ./build/app.zip